### ISSUE TITLE
Due date enforced on assignments with no due date

### ISSUE THREAD

**Issue by mkpelletier** [jmcgettrick/moodle-plagiarism_turnitin-archived#13]
The plagiarism plugin returns an error to students when they submit to an assignment which has no due date set if the submission takes place more than 6 months after the assignment was configured.

Steps to reproduce:
1. Create an assignment with no due date with Tii PP configured.
2. submit to same 181 days after the assignment was configured.
3. student receives an error: Turnitin has returned an error with your submission: The due date for this assignment has passed and you have already made a submission.

WORKAROUND:
Edit the assignment and set a due date in the distant future.  The student will be permited to make a submission.

Moodle 2.8.6+ (Build: 20150625)
TIi PP 2015040106	2.3+

**Comment by jmcgettrick** [comment]
Hi Mathieu, this has been fixed in develop with https://github.com/jmcgettrick/moodle-plagiarism_turnitin/commit/a57200edebc88b02473c9ad911444f8634c00480. I'll leave this issue open until we merge the branch into master though.

**Comment by mkpelletier** [comment]
Thanks, John!  There are lots of great fixes in the pipeline.  It's nice to see!

**Comment by mkpelletier** [comment]
oops... clicked the wrong button!

**Comment by jmcgettrick** [comment]
Hi @mkpelletier,
This has been released in 2015040110. Please note that repository has moved to the Turnitin account at: https://github.com/turnitin/moodle-plagiarism_turnitin
