### ISSUE TITLE
Grademark grade returned to gradebook when blind marking on

### ISSUE THREAD

**Issue by micaherne** [jmcgettrick/moodle-plagiarism_turnitin-archived#27]
Hi John, we've noticed that the plagiarism plugin is returning Grademark grades directly to the Moodle gradebook when blind marking is switched on for an assignment and student identities haven't yet been revealed. This isn't good as it's circumventing Moodle's blind marking controls.

When blind marking is switched on, the assignment tool holds any grades in a holding area until student identities are revealed, and only on revealing identities are they actually copied into the gradebook (https://docs.moodle.org/24/en/Assignment_settings#Blind_marking). This is to stop the marker seeing in the gradebook which students have submitted, or linking up the submission to the student.

With the plagiarism plugin making the grades available while identities are still hidden, it's pretty easy for the marker to work out (deliberately or otherwise) which anonymised identity relates to which student, particularly in small classes.

(Just to be clear, this is a completely separate issue from https://github.com/jmcgettrick/MoodleDirectV2/issues/160 where the document viewer leaks the student name)

**Comment by jmcgettrick** [comment]
Hi @micaherne, I've moved this over to new account repo: https://github.com/turnitin/moodle-plagiarism_turnitin/issues/3
